# Generated by Django 5.0.1 on 2024-02-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_photo',
            field=models.ImageField(blank=True, upload_to='manager/static/images/user'),
        ),
    ]
