# Generated by Django 4.2.6 on 2024-06-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_employee_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_photo',
            field=models.ImageField(blank=True, upload_to='static/images/user'),
        ),
    ]
