# Generated by Django 4.2.6 on 2024-06-09 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0007_alter_procedure_status'),
        ('checklist', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], max_length=10)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.procedure')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.checklistquestion')),
            ],
        ),
    ]
