# Generated by Django 4.2.6 on 2024-06-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedureresponse',
            name='return_resone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
