# Generated by Django 4.2.6 on 2024-06-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_procedureresponse_return_resone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedureresponse',
            name='return_resone',
        ),
    ]
