# Generated by Django 4.2.6 on 2024-10-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0007_alter_procedureresponse_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedureresponse',
            name='response',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A'), ('-----', '-----')], max_length=10),
        ),
    ]
