# Generated by Django 4.2.6 on 2024-06-09 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='client_data',
        ),
    ]
