# Generated by Django 4.2.6 on 2024-06-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_procedure_client_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='data_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
