# Generated by Django 4.2.6 on 2024-06-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_procedure_client_name_procedure_data_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='client_name',
            field=models.CharField(max_length=255),
        ),
    ]
