# Generated by Django 4.2.6 on 2024-06-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_procedure_data_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Returned', 'Returned'), ('Reviewed', 'Reviewed'), ('Deleted', 'Deleted')], default='Pending', max_length=10),
        ),
    ]
