# Generated by Django 4.2.6 on 2024-10-06 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checklist', '0005_alter_checklistquestion_options_and_more'),
        ('user', '0007_alter_procedure_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checklist.checklist'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
