# Generated by Django 4.2.6 on 2024-02-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistquestion',
            name='checklist',
        ),
        migrations.DeleteModel(
            name='Checklist',
        ),
        migrations.DeleteModel(
            name='ChecklistQuestion',
        ),
    ]
