# Generated by Django 4.2.6 on 2024-10-06 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_alter_checklistquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistquestion',
            options={},
        ),
        migrations.RemoveField(
            model_name='checklistquestion',
            name='ordering',
        ),
    ]
