# Generated by Django 4.2.6 on 2024-10-06 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_alter_checklistquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistquestion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='checklist.section'),
        ),
    ]
