# Generated by Django 4.2.6 on 2024-10-06 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0007_alter_checklistquestion_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistquestion',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checklist.section'),
        ),
    ]
