# Generated by Django 4.2.6 on 2024-10-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0008_alter_checklistquestion_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistquestion',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='checklistquestion',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
